In [42]:
import pandas as pd
import numpy as np
import pickle 
import streamlit as slt


In [43]:
f = pd.read_csv('Weather_data.csv')
f

temp_max  temp_min  wind  weather  value
0         12.8       5.0   4.7  drizzle      1
1         10.6       2.8   4.5     rain      3
2         11.7       7.2   2.3     rain      3
3         12.2       5.6   4.7     rain      3
4          8.9       2.8   6.1     rain      3
...        ...       ...   ...      ...    ...
1456       4.4       1.7   2.9     rain      3
1457       5.0       1.7   1.3     rain      3
1458       7.2       0.6   2.6      fog      2
1459       5.6      -1.0   3.4      sun      0
1460       5.6      -2.1   3.5      sun      0

[1461 rows x 5 columns]

In [44]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [45]:
y = f['value']
y = y.astype('int')
y

0       1
1       3
2       3
3       3
4       3
       ..
1456    3
1457    3
1458    2
1459    0
1460    0
Name: value, Length: 1461, dtype: int32

In [48]:
x = f[['temp_max','temp_min','wind']]
x = x.astype('int')
x

temp_max  temp_min  wind
0           12         5     4
1           10         2     4
2           11         7     2
3           12         5     4
4            8         2     6
...        ...       ...   ...
1456         4         1     2
1457         5         1     1
1458         7         0     2
1459         5        -1     3
1460         5        -2     3

[1461 rows x 3 columns]

In [65]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)


In [66]:
y_train

1066    2
638     3
799     3
380     0
303     3
       ..
1130    3
1294    0
860     3
1459    0
1126    2
Name: value, Length: 1168, dtype: int32

In [67]:
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [52]:
# y_train_predict_lr = lr.predict(x_train)
# y_test_predict_lr = lr.predict(x_test)

In [53]:
# rf = RandomForestRegressor(max_depth=2 ,random_state= 100)
# rf.fit(x_train,y_train)

RandomForestRegressor(max_depth=2, random_state=100)

In [54]:
# lof = LogisticRegression()
# lof.fit(x_train,y_train)

c:\Users\Amey Rasekar\anaconda3\envs\ml_env\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [55]:
# y_train_predict_rf = rf.predict(x_train)
# y_test_predict_rf = rf.predict(x_test)

In [56]:
# y_train_predict_lr

array([2.03223944, 0.72039064, 2.69722643, ..., 1.19524508, 0.17091885,
       3.02971993])

In [57]:
# y_test_predict_lr

array([ 1.67009953e+00,  2.42915020e+00,  2.49457005e+00,  1.48671842e-01,
        2.00439110e+00,  2.25994350e+00,  2.33688459e+00,  1.78741280e+00,
        6.50372037e-01,  1.59775718e+00,  5.66031526e-01,  2.40410252e+00,
        1.78741280e+00,  1.17532183e+00,  9.67541026e-01,  8.90599929e-01,
        1.05800855e+00,  2.55206481e+00,  2.07440970e+00,  2.29751501e+00,
        2.58963632e+00,  2.12730571e+00,  1.78508905e+00,  6.45773292e-01,
        1.68118177e-01,  1.39050205e+00,  1.30003452e+00,  2.62900591e+00,
        7.92732988e-01,  6.12800527e-01,  2.29931308e+00,  2.25994350e+00,
        2.73939669e+00,  2.32996210e+00,  2.80201587e+00,  7.09552793e-04,
        1.27778752e+00,  2.16487722e+00,  1.05008346e+00,  9.82865532e-01,
        1.08765497e+00,  2.84418613e+00,  2.68470260e+00,  1.95709642e+00,
        1.58755709e+00,  1.53233732e+00,  2.19632172e+00,  1.25786427e+00,
        1.23281659e+00,  9.77741110e-01,  1.52493791e+00,  4.40793157e-01,
       -6.93923856e-01,  

In [58]:
# y_train_predict_rf

array([2.24533081, 2.16877287, 2.26113385, ..., 1.73230738, 0.47228649,
       2.26113385])

In [59]:
from sklearn.metrics import mean_squared_error , r2_score

In [60]:
# lr_mse_tr = mean_squared_error(y_train,y_train_predict_lr)
# lr_r2_tr = r2_score(y_train,y_train_predict_lr)
# lr_mse_ts = mean_squared_error(y_test,y_test_predict_lr)
# lr_r2_ts = r2_score(y_test,y_test_predict_lr)



# rf_mse_tr = mean_squared_error(y_train,y_train_predict_rf)
# rf_r2_tr = r2_score(y_train,y_train_predict_rf)
# rf_mse_ts = mean_squared_error(y_test, y_test_predict_rf)
# rf_r2_ts = r2_score(y_test, y_test_predict_rf)

In [61]:
# model_rl_lr =  pd.DataFrame(['Linear regression',lr_mse_tr,lr_mse_ts,lr_r2_tr,lr_r2_ts]).transpose()
# model_rl_rf =  pd.DataFrame(['RandomForestRegressor', rf_mse_tr,rf_mse_ts,rf_r2_tr,rf_r2_ts]).transpose()
# model_rl_lr.columns= ['Method','Trainig Mse','Test Mse','Trainig R2','Test R2']
# model_rl_rf.columns = ['Method','Trainig Mse','Test Mse','Trainig R2','Test R2']


In [62]:
# model_rl_lr

Method Trainig Mse  Test Mse Trainig R2   Test R2
0  Linear regression    1.384043  1.509736   0.346559  0.267231

In [63]:
# model_rl_rf

Method Trainig Mse  Test Mse Trainig R2   Test R2
0  RandomForestRegressor    1.529057  1.605854   0.278095  0.220578

In [64]:
pickle.dump(lr,open('Lin_reg.pkl','wb'))
# pickle.dump(rf,open('RandomForest.pkl','wb'))
# pickle.dump(lof,open('Log_reg.pkl','wb'))